version: '3'
services:
        web:
                image: snap_shot_v1
                build: .
                ports:
                        - "8055:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
